export const cars = [
  {
    title: "Audi A4",
    type: "Sedan",
    rentPrice: 90.0,
    capacity: 5,
    transmission: "Manual",
    location: "Berlin",
    fuelCapacity: 55,
    description: "Comfortable and stylish.",
    images: ["audi_a4.jpg"],
    ownerId: "user-001",
  },
  {
    title: "BMW 320",
    type: "Sedan",
    rentPrice: 95.0,
    capacity: 5,
    transmission: "Automatic",
    location: "Munich",
    fuelCapacity: 50,
    description: "A driver's car.",
    images: ["bmw_320.jpg"],
    ownerId: "user-001",
  },
  {
    title: "Tesla Model S",
    type: "Electric",
    rentPrice: 120.0,
    capacity: 5,
    transmission: "Automatic",
    location: "San Francisco",
    fuelCapacity: 0,
    description: "Futuristic and fast.",
    images: ["tesla_model_s.jpg"],
    ownerId: "user-001",
  },
  {
    title: "Toyota Prius",
    type: "Hybrid",
    rentPrice: 80.0,
    capacity: 5,
    transmission: "Automatic",
    location: "Tokyo",
    fuelCapacity: 45,
    description: "Eco-friendly and reliable.",
    images: ["toyota_prius.jpg"],
    ownerId: "user-001",
  },
  {
    title: "Ford Mustang",
    type: "Coupe",
    rentPrice: 100.0,
    capacity: 4,
    transmission: "Manual",
    location: "Los Angeles",
    fuelCapacity: 60,
    description: "Classic American muscle.",
    images: ["ford_mustang.jpg"],
    ownerId: "user-001",
  },
  {
    title: "Chevrolet Camaro",
    type: "Coupe",
    rentPrice: 100.0,
    capacity: 4,
    transmission: "Manual",
    location: "New York",
    fuelCapacity: 58,
    description: "Powerful and stylish.",
    images: ["chevrolet_camaro.jpg"],
    ownerId: "admin-001",
  },
  {
    title: "Mercedes-Benz C-Class",
    type: "Sedan",
    rentPrice: 110.0,
    capacity: 5,
    transmission: "Automatic",
    location: "Stuttgart",
    fuelCapacity: 55,
    description: "Luxurious and elegant.",
    images: ["mercedes_c_class.jpg"],
    ownerId: "admin-001",
  },
  {
    title: "Honda Civic",
    type: "Sedan",
    rentPrice: 85.0,
    capacity: 5,
    transmission: "Manual",
    location: "London",
    fuelCapacity: 50,
    description: "Reliable and efficient.",
    images: ["honda_civic.jpg"],
    ownerId: "admin-001",
  },
  {
    title: "Porsche 911",
    type: "Sports",
    rentPrice: 150.0,
    capacity: 2,
    transmission: "Manual",
    location: "Berlin",
    fuelCapacity: 64,
    description: "Fast and luxurious sports car.",
    images: ["porsche_911.jpg"],
    ownerId: "admin-001",
  },
  {
    title: "Lamborghini Huracan",
    type: "Sports",
    rentPrice: 200.0,
    capacity: 2,
    transmission: "Automatic",
    location: "Rome",
    fuelCapacity: 75,
    description: "Exotic and exhilarating.",
    images: ["lamborghini_huracan.jpg"],
    ownerId: "admin-001",
  },
];
